function(check_cli expected_status expected_output)
    execute_process(COMMAND "${BEAM_EXECUTABLE}" ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT "${status}" STREQUAL "${expected_status}")
        message(FATAL_ERROR "CLI ${ARGN}: expected exit ${expected_status}, got ${status}: ${error}")
    endif()
    string(FIND "${output}${error}" "${expected_output}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "CLI ${ARGN}: missing '${expected_output}': ${output}${error}")
    endif()
endfunction()

check_cli(0 "Usage:")
check_cli(0 "Usage:" --help)
check_cli(0 "Beam ${BEAM_VERSION}" --version)
if(BEAM_HAS_QUIC)
    check_cli(2 "missing required option" send 127.0.0.1:4269 hello.txt)
    check_cli(2 "missing required option" receive --listen 4269)
    check_cli(2 "unknown option" receive --insecure)
    check_cli(2 "duplicate option" send --ca a --ca b)
    check_cli(2 "duplicate option" send --no-progress --no-progress)
    check_cli(2 "missing required option" send --no-progress)
    check_cli(0 "Ctrl-C" --help)
    check_cli(2 "invalid endpoint" send 127.0.0.1:99999 hello.txt --cert c --key k --ca ca)
    check_cli(2 "invalid listen port" receive --listen 0 --output . --cert c --key k --ca ca)
else()
    check_cli(1 "available in macOS/Linux" send 127.0.0.1:4269 hello.txt)
endif()
check_cli(2 "Unsupported command" unknown)
check_cli(2 "Unsupported command" --version extra)
check_cli(2 "Unsupported command" --help extra)
