function(check_cli expected_status expected_output)
    execute_process(COMMAND "${BEAM_EXECUTABLE}" ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT "${status}" STREQUAL "${expected_status}")
        message(FATAL_ERROR "CLI ${ARGN}: expected exit ${expected_status}, got ${status}: ${error}")
    endif()
    string(FIND "${output}${error}" "${expected_output}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "CLI ${ARGN}: missing '${expected_output}': ${output}${error}")
    endif()
endfunction()

check_cli(0 "Usage:")
check_cli(0 "Usage:" --help)
check_cli(0 "Beam ${BEAM_VERSION}" --version)
if(BEAM_HAS_QUIC)
    check_cli(2 "missing required option" send 127.0.0.1:4269 hello.txt)
    check_cli(2 "missing required option" receive --listen 4269)
    check_cli(2 "unknown option" receive --insecure)
    check_cli(2 "duplicate option" send --ca a --ca b)
    check_cli(2 "duplicate option" send --no-progress --no-progress)
    check_cli(2 "send requires" send --no-progress)
    check_cli(2 "identity requires" identity)
    check_cli(2 "identity requires" identity rotate)
    check_cli(2 "unknown option" identity init --insecure)
    check_cli(2 "missing value" identity init --state-dir)
    check_cli(2 "duplicate option" peers --state-dir a --state-dir b)
    check_cli(2 "one lowercase peer name" pair ../bad --cert a --fingerprint b)
    check_cli(2 "missing required option --fingerprint" pair laptop --cert a)
    check_cli(2 "missing required option --endpoint" peer laptop)
    check_cli(2 "peers takes no positional" peers extra)
    check_cli(2 "manual credentials cannot be combined" send 127.0.0.1:4269 a --cert c --key k --ca ca --state-dir state)
    check_cli(2 "omit --server-name" send a laptop --server-name spoofed)
    check_cli(2 "invalid peer name" send a ../bad)
    check_cli(0 "Ctrl-C" --help)
    check_cli(2 "invalid endpoint" send 127.0.0.1:99999 hello.txt --cert c --key k --ca ca)
    check_cli(2 "invalid listen port" receive --listen 0 --output . --cert c --key k --ca ca)
else()
    check_cli(1 "available in macOS/Linux" send 127.0.0.1:4269 hello.txt)
endif()
if(BEAM_HAS_DISCOVERY)
    check_cli(2 "devices accepts only" devices extra)
    check_cli(2 "invalid discovery timeout" devices --timeout 0)
    check_cli(2 "invalid discovery timeout" devices --timeout 61)
    check_cli(2 "devices accepts only" devices --timeout)
    check_cli(2 "devices accepts only" devices --timeout 1 --timeout 2)
    if(BEAM_HAS_QUIC)
        check_cli(2 "name must be" receive --listen 4269 --output . --cert c --key k --ca ca --name "bad\tname")
        check_cli(2 "cannot be combined" receive --listen 4269 --output . --cert c --key k --ca ca --name Beam --no-discovery)
        check_cli(2 "unknown option" send --no-discovery)
        check_cli(2 "duplicate option" receive --no-discovery --no-discovery)
    endif()
else()
    check_cli(1 "LAN discovery is disabled" devices)
endif()
check_cli(2 "Unsupported command" unknown)
check_cli(2 "Unsupported command" --version extra)
check_cli(2 "Unsupported command" --help extra)
